
# See https://github.com/JohnnyMorganz/StyLua/blob/main/docs/configuration.md

column_width = 80
line_endings = "Unix"
indent_type = "Spaces"
indent_width = 2
quote_style = "AutoPreferDouble"
call_parentheses = "Always"
